### PR TITLE
Internet break backup

### PR DESCRIPTION
**Pull request by bond400apm**
Added a local db using json. This will help when internet breaks down

### CODE REVIEW

**Comment by pershint** [comment]
Please make changes to the PR as discussed at our meeting today.

**Comment by bond400apm** [comment]
Still having problems, just pushed it to visually see the change .

**Comment by bond400apm** [comment]
Interpreter shut down problem solved. Turns out I didn't have a well defined default_channeldb when localcdb.json is empty.

**Comment by pershint** [comment]
Hey Tianqi,

This looks good to me, just one thing.  We don't need to track the changes to localcdb.json on github, and it also seems that localcdb.json only has the entries for IOS3 right now.  Here's what I would suggest:

  - If you do want to have a copy of localcdb.json saved onto github, I would have the json.dump function save the entire channeldb file, not just the entry associated with IOS 3.  This way, any IOS can use the localcdb.json file that is saved.
  - If you do not want to have a copy of localdb.json in the repository, look up how to use a .gitignore file.  You can add the localcdb.json file to the .gitignore file so github will not save it in future commits.  You'll also have to remove the localcdb.json from your next commit so github stops keeping it.

**Comment by bond400apm** [comment]
I put it into .gitignore. This way, I think each IOS will have its own localcdb associated with their IOS number.

**Comment by pershint** [comment]
Looks good, thanks Tianqi.

**Pull request merged**
